from routes.organization_detail import organization_detail
from routes.hsn_master import hsn_master
from routes.material_group_master import material_group_masters, material_group_add
from routes.material_basic_detail import material_basic_detail
from routes.product_group_master import product_group_masters, product_group_add
from routes.product_basic_detail import product_basic_detail
